# Custom Language File for Launcher Customizer

[ejs.app]
title = "minimanimo"

[ejs.landing]
mediaGitHubURL = "https://github.com/mini0316/minimanimo"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/MrZ7c4n7Yk"

[ejs.settings]
sourceGithubLink = "https://github.com/mini0316/minimanimo"
supportLink = "https://github.com/mini0316/minimanimo/issues"

[ejs.welcome]
welcomeHeader = "welcome To minimanimo"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
